import {$,api,esc,humanStatus,initials,toast} from '/static/shared.js';
let state=null;let routeId='r3';let selectedStop=null;
function currentRoute(){return state.routes[routeId]}
function assigned(){return state.volunteers[currentRoute().volunteer_id]}
function summary(){return state.route_summaries[routeId]}
function nextStop(){const r=currentRoute();return r.stop_ids.map(id=>state.stops[id]).find(s=>!s.outcome)}
function routeHome(){const r=currentRoute(),v=assigned(),s=summary(),n=nextStop();
 $('#app').innerHTML=`<section class="greeting"><div class="sub">Today</div><h1>Hi, ${esc(v?.name||'Volunteer')}</h1><p>${r.status==='complete'?'Your route is complete.':'Here’s your delivery route.'}</p></section>
 <section class="route-hero"><div class="sub">${r.start_time} start · ${s.total} stops</div><h2>${esc(r.name)}</h2><div class="big-progress"><div style="display:flex;justify-content:space-between"><strong>${s.delivered+s.exceptions} of ${s.total} accounted for</strong><span class="sub">${s.percent}%</span></div><div class="progress"><span style="width:${s.percent}%"></span></div></div><div class="meta-row"><span>◷ Est. finish ${r.estimated_finish}</span><span>● ${humanStatus(r.status)}</span></div></section>
 <div class="section-title">Your stops</div><div class="route-stops">${r.stop_ids.map(id=>{const x=state.stops[id];return `<button class="vol-stop ${x.outcome?'done':''} ${n?.id===x.id?'current':''}" data-stop="${x.id}"><div class="stop-num">${x.outcome==='delivered'?'✓':x.sequence}</div><div class="grow"><strong>${esc(x.recipient)}</strong><div class="sub">${esc(x.address)}</div></div><div class="sub">${x.outcome?humanStatus(x.outcome):n?.id===x.id?'Next':'Pending'} ›</div></button>`}).join('')}</div>`;
 $('#bottom').innerHTML=r.status==='complete'?`<div class="bottom-action"><a class="btn btn-sage" href="/volunteer">Route complete · Thank you</a></div>`:r.started_at?(n?`<div class="bottom-action"><button class="btn btn-primary" id="nextBtn">Continue to ${esc(n.recipient)}</button></div>`:`<div class="bottom-action"><div class="btn btn-secondary">Waiting for coordinator review</div></div>`):`<div class="bottom-action"><button class="btn btn-primary" id="startBtn">Start route</button></div>`;
 document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>showStop(b.dataset.stop));
 const start=$('#startBtn');if(start)start.onclick=startRoute;const next=$('#nextBtn');if(next)next.onclick=()=>showStop(n.id);
}
async function startRoute(){try{await api(`/api/routes/${routeId}/start`,{method:'POST',body:JSON.stringify({volunteer_id:assigned().id})});toast('Route started. Drive safely.');await refresh();showStop(nextStop().id)}catch(e){toast(e.message,true)}}
function showStop(id){selectedStop=id;const x=state.stops[id],r=currentRoute();
 $('#app').innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><button class="btn btn-ghost" id="backBtn">← Route</button><div class="sub">Stop ${x.sequence} of ${r.stop_ids.length}</div><span></span></div>
 <section class="care-top"><div class="care-avatar">${initials(x.recipient)}</div><h1>${esc(x.recipient)}</h1>${x.accessibility?`<span class="access-tag">ⓘ ${esc(x.accessibility)}</span>`:''}<p class="sub">${esc(x.address)}</p></section>
 ${x.conversation_starter?`<div class="warm-note"><label>Conversation starter</label><p>“${esc(x.conversation_starter)}”</p></div>`:''}
 <div class="info-box"><label>Delivery instructions</label><p>${esc(x.delivery_notes||'No special access instructions.')}</p></div>
 <div class="meal-grid"><div class="info-box"><label>Meal</label><p>${esc(x.meal_items||'1 meal')}</p></div><div class="info-box"><label>Diet</label><p>${esc(x.diet||'Regular')}</p></div></div>
 ${x.outcome?`<div class="info-box"><label>Recorded outcome</label><p>${esc(humanStatus(x.outcome))}</p>${x.outcome_note?`<div class="sub" style="margin-top:5px">${esc(x.outcome_note)}</div>`:''}</div>`:''}`;
 $('#bottom').innerHTML=x.outcome?`<div class="bottom-action"><button class="btn btn-secondary" id="backBottom">Back to route</button></div>`:`<div class="bottom-action"><button class="btn btn-sage" id="deliveredBtn">✓ Delivered</button><button class="btn btn-ghost" id="problemBtn" style="width:100%;margin-top:7px;color:var(--red)">Problem / no answer</button></div>`;
 $('#backBtn').onclick=routeHome;const bb=$('#backBottom');if(bb)bb.onclick=routeHome;const d=$('#deliveredBtn');if(d)d.onclick=()=>submitOutcome('delivered','Meal handed to recipient.');const p=$('#problemBtn');if(p)p.onclick=openProblem;
}
function openProblem(){const x=state.stops[selectedStop];$('#sheetRoot').innerHTML=`<div class="sheet-backdrop" id="sheetBg"><div class="sheet"><div class="sheet-handle"></div><h2>What happened?</h2><p>Choose the closest factual outcome. Porchlight will follow your organization’s configured process.</p><div class="choice-list">${[['no_answer','No answer'],['recipient_declined','Recipient declined'],['could_not_access','Could not access property'],['meal_issue','Problem with meal'],['welfare_concern','Welfare concern'],['other','Something else']].map(([v,l])=>`<button class="choice" data-choice="${v}">${l}</button>`).join('')}</div><div id="protocolArea"></div><label class="sub" for="outcomeNote">Factual note</label><textarea id="outcomeNote" class="field" placeholder="What did you observe? Avoid diagnoses or assumptions."></textarea><button class="btn btn-primary" id="submitProblem" style="width:100%;margin-top:12px" disabled>Submit outcome</button><button class="btn btn-ghost" id="cancelSheet" style="width:100%;margin-top:6px">Cancel</button></div></div>`;
 let choice=null;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choice=b.dataset.choice;document.querySelectorAll('[data-choice]').forEach(x=>x.classList.toggle('selected',x===b));const pr=state.protocols[choice];$('#protocolArea').innerHTML=pr?`<div class="protocol"><strong>${esc(pr.title)} protocol</strong><ol>${pr.ordered_steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><label style="display:flex;gap:8px;align-items:flex-start;font-weight:700"><input type="checkbox" id="protocolCheck"> I completed the steps above.</label></div>`:'';$('#submitProblem').disabled=false});
 $('#cancelSheet').onclick=()=>$('#sheetRoot').innerHTML='';$('#sheetBg').onclick=e=>{if(e.target.id==='sheetBg')$('#sheetRoot').innerHTML=''};$('#submitProblem').onclick=async()=>{if(!choice)return;const pr=state.protocols[choice];const checked=!pr||$('#protocolCheck')?.checked;if(pr&&!checked){toast('Confirm that you completed the protocol first.',true);return}const note=$('#outcomeNote').value.trim();await submitOutcome(choice,note,!!pr)};
}
async function submitOutcome(outcome,note='',protocol_completed=false){try{await api(`/api/routes/${routeId}/stops/${selectedStop}/outcome`,{method:'POST',body:JSON.stringify({outcome,note,protocol_completed})});$('#sheetRoot').innerHTML='';toast(outcome==='delivered'?'Delivery recorded.':'Outcome recorded. The coordinator will see anything that needs review.');await refresh();routeHome()}catch(e){toast(e.message,true)}}
async function refresh(){state=await api('/api/state');routeHome()}refresh();
